# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

on: push

jobs:
  webserver:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v2
    - name: Install node packages and create CA certificate
      run: ./build
      working-directory: webserver
    - name: Check JavaScript code
      run: npx eslint webserver.js
      working-directory: webserver
    - name: Execute test
      run: ./test
      working-directory: webserver

  signalingserver:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v2
    - name: Install node packages
      run: ./build
      working-directory: signalingserver
    - name: Check JavaScript code
      run: npx eslint app.js
      working-directory: signalingserver
    - name: Execute test
      run: ./test
      working-directory: signalingserver

  frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v2
    - name: Check JavaScript code
      run: npx eslint *.js
      working-directory: frontend
