# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

on: push

jobs:
  webserver:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./build
      working-directory: webserver
    - run: npx eslint webserver.js
      working-directory: webserver
    - run: ./test
      working-directory: webserver

  signalingserver:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./build
      working-directory: signalingserver
    - run: ./test
      working-directory: signalingserver
