# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  signalingserver:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
      working-directory: signalingserver
